version: "3.9"
services:

  test:
    env_file: ./.env_test
    build: 
      context: .
      target: test
    image: todo-app:test
    volumes:
      - ./todo_app:/appcode/todo_app
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  dev:
    environment:
      FLASK_APP: todo_app/app
      FLASK_ENV: development
      MONGO_CON_STRING: mongodb://root:example@mongo:27017/
      MONGO_DB_NAME: dev_items
    build: 
      context: .
      target: development
    image: todo-app:dev
    ports:
      - "5000:5000"
    volumes:
      - ./todo_app:/appcode/todo_app
  
  prod:
    env_file: ./.env
    build: 
      context: .
      target: production
    image: todo-app:prod
    ports:
      - "8000:8000"
