name: CI - To-Do app

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.dockerignore'
      - 'docker-compose.yml'
      - 'ansible/**'
  pull_request:
    branches:
      -  main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build the CI test image
      run: docker build --target ci-test --tag todo-app:ci-test .
    - name: Run the CI test image
      run: docker run --env-file ./.env_test todo-app:ci-test
      
  publish:
    name: Push image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/module-11') }}
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the CI prod image 
        run: docker build --target production --tag simeonp901/todo_app:latest --tag simeonp901/todo_app:"$GITHUB_SHA" .
      - name: Push the CI prod image to Docker Hub
        run: docker push simeonp901/todo_app --all-tags

  deploy:
    name: Deploy to Azure  
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Restart and Pull latest image
        run: curl -dH -X POST ${{ secrets.AZURE_WEBHOOKURL }}