name: CI - To-Do app

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - '.dockerignore'
      - 'docker-compose.yml'
      - 'ansible/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - '.dockerignore'
      - 'docker-compose.yml'
      - 'ansible/**'

jobs:
  build:
      name: Build and test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Build the CI test image
        run: docker build --target ci-test --tag todo-app:ci-test .

      - name: Run the CI test image
        run: docker run --env-file ./.env_test todo-app:ci-test
      
  publish:
    name: Push image to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the CI prod image 
        run: docker build --target production --tag CreaTiVeUK/todo_app:latest --tag CreaTiVeUK/todo_app:"$GITHUB_SHA" .
      
      - name: Push the CI prod image to Docker Hub
        run: docker push CreaTiVeUK/todo_app --all-tags

  deploy:
    name: Deploy to Azure via Heroku      
    needs: publish
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2